Repository sprint-part2-team14/OpenMind, pull requests merged in 2024-03, with the labels that each got.

#13 [#9] (공용 컴포넌트) Badge 제작
  openmind/.eslintrc.json
  openmind/.prettierrc.json
  openmind/package-lock.json
  openmind/package.json
  openmind/src/App.js
  openmind/src/App.jsx
  openmind/src/Components/BadgeBrown.jsx
  openmind/src/Components/BadgeGray.jsx
  openmind/src/Components/componetstest.md
  openmind/src/Styles/Badge.css
  openmind/src/Styles/Css/Reset.css
  openmind/src/index.js
Labels: 공용 컴포넌트

#16 [#15] UserCard
  openmind/src/App.jsx
  openmind/src/Components/UserCard.jsx
  openmind/src/Styles/Badge.css
  openmind/src/Styles/Css/Reset.css
  openmind/src/Styles/UserCard.module.css
Labels: 공용 컴포넌트

#14 [#11] Toast
  openmind/package-lock.json
  openmind/package.json
  openmind/src/Components/Toast.jsx
  openmind/src/Styles/Css/Reset.css
  openmind/src/Styles/Toast.css
Labels: 공용 컴포넌트

#20 [#17] PageNation
  openmind/.prettierrc.json
  openmind/src/App.jsx
  openmind/src/Components/PageNation.jsx
  openmind/src/Styles/PageNation.module.css
Labels: 공용 컴포넌트

#25 [#8] FeedCard
  openmind/src/Components/EmptyAnswer.jsx
  openmind/src/Components/FeedCard.jsx
  openmind/src/Components/FeedFooter.jsx
  openmind/src/Components/FeedQuestion.jsx
  openmind/src/Components/RejectAnswer.jsx
  openmind/src/Components/SentAnswer.jsx
  openmind/src/Styles/Css/Reset.css
  openmind/src/Styles/EmptyAnswer.module.css
  openmind/src/Styles/FeedCard.module.css
  openmind/src/Styles/FeedFooter.module.css
  openmind/src/Styles/FeedQuestion.module.css
  openmind/src/Styles/RejectAnswer.module.css
  openmind/src/Styles/SentAnswer.module.css
Labels: 공용 컴포넌트

#30 [#29] Component refactor
  openmind/.eslintrc.json
  openmind/package-lock.json
  openmind/package.json
  openmind/src/App.jsx
  openmind/src/Components/BadgeBrown.jsx
  openmind/src/Components/BadgeGray.jsx
  openmind/src/Components/BoxButton.jsx
  openmind/src/Components/EmptyAnswer.jsx
  openmind/src/Components/FeedCard.jsx
  openmind/src/Components/FeedFooter.jsx
  openmind/src/Components/FeedQuestion.jsx
  openmind/src/Components/FloatingButton.jsx
  openmind/src/Components/Input.jsx
  openmind/src/Components/PageNation.jsx
  openmind/src/Components/QuestionReaction.jsx
  openmind/src/Components/Reaction.jsx
  openmind/src/Components/RejectAnswer.jsx
  openmind/src/Components/SentAnswer.jsx
  openmind/src/Components/Toast.jsx
  openmind/src/Styles/Badge.module.css
  openmind/src/Styles/BoxButton.module.css
  openmind/src/Styles/Css/Reset.css
  openmind/src/Styles/EmptyAnswer.module.css
  openmind/src/Styles/FeedCard.module.css
  openmind/src/Styles/FeedFooter.module.css
  openmind/src/Styles/FeedQuestion.module.css
  openmind/src/Styles/FloatingButton.module.css
  openmind/src/Styles/Input.css
  openmind/src/Styles/InputField.module.css
  openmind/src/Styles/InputTextArea.module.css
  openmind/src/Styles/PageNation.module.css
  openmind/src/Styles/Reaction.module.css
  openmind/src/Styles/RejectAnswer.module.css
  openmind/src/Styles/SentAnswer.module.css
  openmind/src/Styles/ShareButton.module.css
  openmind/src/Styles/Toast.module.css
  openmind/src/Styles/UserCard.module.css
  openmind/src/Utils/ReactionAPI.js
Labels: 공용 컴포넌트

#38 [#37] API
  openmind/package-lock.json
  openmind/package.json
  openmind/src/Utils/API.js
Labels: API

#35 [#12] Dropdown
  openmind/src/Assets/Icon/iconArrowDown.svg
  openmind/src/Components/DropDown.jsx
  openmind/src/Components/DropDownList.jsx
  openmind/src/Components/DropDownMake.jsx
  openmind/src/Styles/DropDown.module.css
Labels: 공용 컴포넌트

#36 [#24] 페이지 레이아웃
  openmind/src/App.jsx
  openmind/src/index.js
Labels: 페이지

#34 [#28] 질문 피드 페이지와 답변 페이지 공통 레이아웃 구현
  openmind/src/Components/FeedCard.jsx
  openmind/src/Components/QuestionReaction.jsx
  openmind/src/Layout/PostnAnswerLayout.jsx
  openmind/src/Styles/Badge.module.css
  openmind/src/Styles/EmptyAnswer.module.css
  openmind/src/Styles/FeedCard.module.css
  openmind/src/Styles/FeedQuestion.module.css
  openmind/src/Styles/InputField.module.css
  openmind/src/Styles/InputTextArea.module.css
  openmind/src/Styles/PostnAnswerLayout.module.css
  openmind/src/Styles/Reaction.module.css
  openmind/src/Styles/RejectAnswer.module.css
  openmind/src/Styles/SentAnswer.module.css
  openmind/src/Styles/Toast.module.css
Labels: 페이지

#43 Refactor: 라우터 수정
  openmind/src/App.jsx
Labels: 페이지

#47 [#46] Refactor: userCard 컴포넌트 수정
  openmind/src/Components/UserCard.jsx
  openmind/src/Utils/API.js
Labels: 공용 컴포넌트

#49 [#48] Refactor: userCard 컴포넌트 수정
  openmind/src/Components/UserCard.jsx
Labels: 공용 컴포넌트

#52 [#12] Dropdown 수정
  openmind/src/Components/DropDown.jsx
  openmind/src/Components/DropDownData.jsx
  openmind/src/Components/DropDownList.jsx
Labels: 공용 컴포넌트

#53 [#50] Pagenation 수정
  openmind/src/Components/PageNation.jsx
  openmind/src/Pages/MainPage.jsx
  openmind/src/Styles/PageNation.module.css
Labels: 공용 컴포넌트

#54 [#39] ListPage implement
  openmind/public/index.html
  openmind/src/Components/DropDown.jsx
  openmind/src/Components/DropDownData.jsx
  openmind/src/Components/DropDownList.jsx
  openmind/src/Pages/AnswerPage.jsx
  openmind/src/Pages/ListPage.jsx
  openmind/src/Pages/PostPage.jsx
  openmind/src/Styles/BoxButton.module.css
  openmind/src/Styles/ListPage.module.css
  openmind/src/Utils/API.js
Labels: 페이지

#56 [#31] MainPage
  openmind/src/Pages/MainPage.jsx
  openmind/src/Styles/MainPage.module.css
Labels: 페이지

#57 [#55] 버튼 컴포넌트 프롭 추가
  openmind/src/Components/BoxButton.jsx
  openmind/src/Components/FloatingButton.jsx
  openmind/src/Components/ShareButton.jsx
  openmind/src/Styles/BoxButton.module.css
  openmind/src/Styles/FloatingButton.module.css
Labels: 공용 컴포넌트

#60 [#58] Modal Page
  openmind/public/index.html
  openmind/src/App.jsx
  openmind/src/Hooks/useModal.js
  openmind/src/Pages/ModalPage.jsx
  openmind/src/Styles/InputTextArea.module.css
  openmind/src/Styles/ModalPage.module.css
  openmind/src/Utils/ModalPortal.js
Labels: 페이지

#59 [#44] AnswerPage
  openmind/src/Components/QuestionReaction.jsx
  openmind/src/Components/Reaction.jsx
  openmind/src/Layout/PostnAnswerLayout.jsx
  openmind/src/Pages/AnswerFeedCard.jsx
  openmind/src/Pages/AnswerFeedCardRender.jsx
  openmind/src/Pages/AnswerPage.jsx
  openmind/src/Styles/PostnAnswerLayout.module.css
Labels: 페이지

#63 [#40] Postpage
  openmind/public/index.html
  openmind/src/Components/FeedCard/FeedCard.jsx
  openmind/src/Components/Reaction/QuestionReaction.jsx
  openmind/src/Components/Reaction/Reaction.jsx
  openmind/src/Components/Toast.jsx
  openmind/src/Components/UserCard.jsx
  openmind/src/Layout/PostnAnswerLayout.jsx
  openmind/src/Pages/PostPage.jsx
  openmind/src/Styles/EmptyAnswer.module.css
  openmind/src/Styles/FeedCard.module.css
  openmind/src/Styles/PostPage.module.css
  openmind/src/Styles/PostnAnswerLayout.module.css
  openmind/src/Styles/RejectAnswer.module.css
  openmind/src/Styles/SentAnswer.module.css
  openmind/src/Utils/API.js
  openmind/src/Utils/processTime.js
Labels: 페이지

#68 Refactor: InputTextArea 리팩토링 완
  openmind/src/Components/Input/InputTextArea.jsx
Labels: 공용 컴포넌트

#70 [#31] MainPage 2차
  openmind/src/Assets/Images/imageMainPage.png
  openmind/src/Assets/Images/imageMainPage.svg
  openmind/src/Components/Input/InputField.jsx
  openmind/src/Components/InputField.jsx
  openmind/src/Components/UserCard.jsx
  openmind/src/Layout/PostnAnswerLayout.jsx
  openmind/src/Pages/MainPage.jsx
  openmind/src/Styles/BoxButton.module.css
  openmind/src/Styles/DropDown.module.css
  openmind/src/Styles/InputField.module.css
  openmind/src/Styles/MainPage.module.css
  openmind/src/Utils/API.js
Labels: 페이지

#69 [#66] PostPage_plus
  openmind/package-lock.json
  openmind/package.json
  openmind/public/index.html
  openmind/src/Components/Button/FloatingButton.jsx
  openmind/src/Components/Button/ShareButton.jsx
  openmind/src/Components/Toast.jsx
  openmind/src/Hooks/useModal.js
  openmind/src/Layout/PostnAnswerLayout.jsx
  openmind/src/Pages/ModalPage.jsx
  openmind/src/Pages/PostPage.jsx
  openmind/src/Styles/FloatingButton.module.css
  openmind/src/Styles/ModalPage.module.css
  openmind/src/Styles/PostPage.module.css
  openmind/src/Styles/ShareButton.module.css
  openmind/src/Styles/Toast.module.css
  openmind/src/Utils/ModalPortal.js
Labels: 페이지

#75 [#73] Modal Page Refactor
  openmind/src/App.jsx
  openmind/src/Components/Input/InputTextArea.jsx
  openmind/src/Pages/MainPage.jsx
  openmind/src/Pages/ModalPage.jsx
  openmind/src/Styles/BoxButton.module.css
  openmind/src/Styles/InputTextArea.module.css
  openmind/src/Styles/ModalPage.module.css
  openmind/src/Styles/UserCard.module.css
Labels: 페이지

#77 [#74] ListPage 수정
  openmind/src/Pages/ListPage.jsx
  openmind/src/Styles/BoxButton.module.css
  openmind/src/Styles/ListPage.module.css
  openmind/src/Styles/UserCard.module.css
Labels: 페이지

#79 [#78] Delete 버튼 컴포넌트 생성 & 버튼 수정
  openmind/src/Components/Button/DeleteButton.jsx
  openmind/src/Pages/ListPage.jsx
  openmind/src/Styles/BoxButton.module.css
  openmind/src/Styles/DeleteButton.module.css
Labels: 공용 컴포넌트

#76 [#72] PostPage 수정 및 완성
  openmind/public/favicon.ico
  openmind/public/index.html
  openmind/src/App.jsx
  openmind/src/Components/FeedCard/FeedCard.jsx
  openmind/src/Components/UserCard.jsx
  openmind/src/Hooks/useModal.js
  openmind/src/Layout/PostnAnswerLayout.jsx
  openmind/src/Pages/ListPage.jsx
  openmind/src/Pages/PostPage.jsx
  openmind/src/Styles/DropDown.module.css
  openmind/src/Styles/ModalPage.module.css
  openmind/src/Styles/PostnAnswerLayout.module.css
  openmind/src/Styles/Toast.module.css
  openmind/src/Utils/API.js
Labels: 페이지

#82 [#81} PostPage Refactor
  openmind/src/Pages/ModalPage.jsx
  openmind/src/Styles/UserCard.module.css
Labels: 페이지

#85 [#84] AnswerPage Refactor
  openmind/.eslintrc.json
  openmind/.prettierrc.json
  openmind/src/App.jsx
  openmind/src/Components/AnswerPage/AnswerDeleteButton.jsx
  openmind/src/Components/AnswerPage/AnswerFeedCardRender.jsx
  openmind/src/Components/AnswerPage/AnswerKebab.jsx
  openmind/src/Layout/AnswerLayout.jsx
  openmind/src/Pages/AnswerFeedCard.jsx
  openmind/src/Pages/AnswerFeedCardRender.jsx
  openmind/src/Pages/AnswerPage.jsx
  openmind/src/Styles/Kebab.module.css
  openmind/src/Utils/API.js
Labels: 페이지
